ARM_CLIENT_ID=
ARM_CLIENT_SECRET=
ARM_TENANT_ID=
ARM_SUBSCRIPTION_ID=
ARM_SP_OBJECT_ID=
docker run \
  -e AZ_CLIENT_ID=${ARM_CLIENT_ID} \
  -e AZ_CLIENT_SECRET=${ARM_CLIENT_SECRET} \
  -e AZ_TENANT_ID=${ARM_TENANT_ID} \
  -e AZ_SP_OBJECT_ID=${ARM_SP_OBJECT_ID} \
  -e AZ_SUBSCRIPTION_ID=${ARM_SUBSCRIPTION_ID} \
  -it azcmdv1 /aks.sh AKSNAME RG AGENTPOOLNAME VMSIZE MINCOUNT MAXCOUNT
exit
# 
# azcmdv1 /tm.sh janle westus2 mirtestbunny mirtestbunny su3bunny 40.70.209.163

